#!/usr/bin/ash

run_hook() {
  for file in /sys/devices/system/cpu/cpufreq/* ; do
  	echo 3000000 > $file/scaling_max_freq
#    cat $file/scaling_min_freq > $file/scaling_max_freq
  done
}

# vim: set ft=sh ts=4 sw=4 et:
