alias timer="time python -c \"input('Press [Enter] or [Ctrl+C] to stop...')\""
alias wifi="python3 ~/Documents/dotfiles/wifimanager.py"
alias dice="python3 ~/Documents/dotfiles/dice.py"
alias weather="curl http://wttr.in/"
alias g="git"
alias gs="git status"
alias ga="git add"
alias n="nano"

if [ $IS_SERVER -ne 1 ]
then
	alias gc="git commit -S"
else
	alias gc="git commit"
fi

alias ipa="ip a"
alias gcm="gc -m"
alias gcam="gc -am"
alias gcam-s="git commit -am"
alias gp="git push"
alias gl="git pull"
alias gf="git fetch"
alias go="git log"
alias gog="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
gd() {
	g diff --color $@ | more
}
alias gy="gl && gp"
alias g...="gcam ... && gy"
alias g...-s="git commit -am ... && gy"
alias fb="llc-3.5 llvm_out.ir&&gcc llvm_out.ir.s&&mv a.out out"
alias pp="pipenv run python"
alias ssh="TERM=xterm ssh"
alias sshuttle="python3 -m sshuttle"
alias c="clear"
alias p="python -q"
alias l="ls"
alias ll="ls -lh"
alias rcon="p ~/.config/i3/clubby_remote.py"
alias ssh-clear-masters="rm ~/.ssh/controlmasters/*"
alias nuclear-option="~/.config/i3/nuclear-option.sh"
alias acmpaste="curl --data-binary @- https://p.acm.umn.edu/"
alias aru="~/Documents/arduino-1.8.5/arduino --port /dev/ttyACM0 --board arduino:avr:leonardo --verbose-upload --upload"
alias sshuttle-home="sshuttle --dns -r scriber 0/0 -x home.louis.goessling.com"
alias ssh-start-agent="ssh-agent -k ; ssh-agent > ~/.ssh-agent-info && source ~/.ssh-agent-info && ssh-add"
alias kill-agents="bash ~/.config/i3/paranoia.sh"
alias kb=keybase
alias sshuttle-acm="sshuttle --dns -r hylaea 0/0 -x 160.94.179.187"
alias sshuttle-acm-mgmt="sshuttle -r lightman@160.94.179.147 10.99.99.0/24"
alias sshuttle-dept-db="sshuttle -r argo 192.168.216.42"

genpasswd () {
	echo $(head /dev/urandom -c ${1:-20} | base64 | head - -c ${1:-20})
}

batt () {
	upower -i $(upower -e | grep BAT)
}

runc () {
	gcc -Wall -Wextra -g $1 && ./a.out $2
}

clubbyplay () {
	scp $1 clubby:
	ssh clubby mpv $1 $2>1 1>/dev/null
}

alias clp=clubbyplay

getcert () {
	echo | openssl s_client -showcerts -servername $1 -connect $1:443 2>/dev/null | openssl x509 -inform pem -noout -text
}

alias d="banner -l d"
alias D="banner -l D"
alias f="banner -l f"
alias F="banner -l F"


alias neofetch="neofetch --disable theme --disable icons"

alias resource="source ~/.bashrc"
alias nbfc=/opt/nbfc/nbfc.exe

vpn () {
	sudo systemctl $1 openvpn-client@scriber
	/usr/bin/pkill -RTMIN+3 i3blocks
}

vpn-set-noleak-off () {
	sudo ufw default allow incoming
	/usr/bin/pkill -RTMIN+3 i3blocks
	sudo ufw default allow outgoing
	sudo ufw delete deny 53
	sudo ufw delete deny 53
}

vpn-set-noleak-on () {
	HOMEIP=$(cat ~/.homeip)
	sudo ufw default deny incoming
	sudo ufw default deny outgoing

	sudo ufw allow in on tun0
	sudo ufw allow out on tun0

	sudo ufw allow in from $HOMEIP
	sudo ufw allow out to $HOMEIP

	sudo ufw deny 53
	sudo ufw allow in on tun0 from 10.0.0.1 port 53
	sudo ufw allow out on tun0 to 10.0.0.1 port 53
	sudo conntrack -D
	sudo conntrack -D
	sudo conntrack -D

	/usr/bin/pkill -RTMIN+3 i3blocks
}

ufw-flush () {
	sudo ufw reset
	sudo ufw enable
	/usr/bin/pkill -RTMIN+3 i3blocks
}

vpn-refresh-ip () {
	HOMEIP=$(dig +short home.louis.goessling.com | sed -n 2p)
	echo "remote $HOMEIP 1194 udp" | sudo tee /etc/openvpn/client/scriber-ip.conf.patch
	echo "$HOMEIP" > ~/.homeip
	/usr/bin/pkill -RTMIN+3 i3blocks
}

cpu-set-govenor-performance () {
	sudo cpupower frequency-set -g performance
}

cpu-set-govenor-powersave () {
	sudo cpupower frequency-set -g powersave
}

cpu-set-upper-limit () {
	sudo cpupower frequency-set -u $1
}

cpu-set-lower-limit () {
	sudo cpupower frequency-set -d $1
}

cpu-freq-info () {
	cpupower frequency-info | egrep "should be within|kernel"
}

alias share="~/.config/i3/share.py"
alias rj="java -Xss512M -jar"
alias jr=rj
alias sv-confirm-self-build="mv build/silver.composed.Default.jar jars/"
alias sv-revert-to-bak="cp JARS-BAK/silver.composed.Default.jar jars/"
alias gf="g fetch"
alias mountmedia="sshfs -o reconnect hylaea:/files/media/ /files/media"
alias mountmedias="sshfs -o reconnect scriber:/files/media/ /files/media"
alias umountmedia="fusermount3 -u /files/media"

umountmediaf () {
	fusermount3 -zu /files/media
	killall -9 sshfs
}

rmountmediaf () {
	umountmediaf
	ssh-clear-masters
	mountmedia
}

alias startx="~/.startx"


alias makeguidlink_hylaea="ssh hylaea ./make_guid_link.sh"
findshitpost () {
	find /files/media/Images -name "*$1*" -name "*$2*" -name "*$3*" -name "*$4*" -name "*$5*" -name "*$6*"
}

export PRINTERBOUNCE=kona
6204print () {
	scp $1 $PRINTERBOUNCE:PRINT && ssh $PRINTERBOUNCE lpr -P cs-p6-204 PRINT
}

alias m=more

cpu-corepwr () {
	for i in {1,5,2,6,3,7} ; do echo $1 | sudo tee /sys/devices/system/cpu/cpu$i/online ; done
}

gpu-off () {
	sudo modprobe acpi_call
	echo \_SB.PCI0.LPC.EC.PUBS._OFF | sudo tee /proc/acpi/call
}

ram-ctrl () {
	for i in {0..275} ; do echo $1 | sudo tee /sys/devices/system/memory/memory$i/online ; done
}

alias laundry="p ~/.config/i3/laundry.py"
alias comstock-laundry="laundry 64 203036"
alias comstock-laundry-w="watch -cn 45 python3 ~/.config/i3/laundry.py 64 203036"

watch-and-run () {
	inotifywait -q -m -e close_write $1 |
	while read -r filename event; do
		$2
	done
}

tex-to-pdf-watch () {
	texi2pdf -b $1
	watch-and-run $1 "texi2pdf -b $1"
}

alias suspend-disable="sudo systemctl mask suspend.target"
alias suspend-enable="sudo systemctl unmask suspend.target"

btspkr-on () {
	pactl load-module module-loopback source="bluez_source.64_C2_DE_DB_63_FC.a2dp_source" source_dont_move="true" sink_input_properties="media.role=music"
}

btspkr-off () {
	pactl unload-module module-loopback
}
