alias timer="time python -c \"input('Press [Enter] or [Ctrl+C] to stop...')\""
alias wifi="python3 ~/Documents/dotfiles/wifimanager.py"
alias dice="python3 ~/Documents/dotfiles/dice.py"
alias weather="curl http://wttr.in/"
alias g="git"
alias gs="git status"
alias ga="git add"

if [ $IS_SERVER -ne 1 ]
then
	alias gc="git commit -S"
else
	alias gc="git commit"
fi

alias ipa="ip a"
alias gcm="gc -m"
alias gcam="gc -am"
alias gcam-s="git commit -am"
alias gp="git push"
alias gl="git pull"
alias gd="g diff --color | more"
alias gy="gl && gp"
alias g...="gcam ... && gy"
alias g...-s="git commit -am ... && gy"
alias fb="llc-3.5 llvm_out.ir&&gcc llvm_out.ir.s&&mv a.out out"
alias pp="pipenv run python"
alias ssh="TERM=xterm ssh"
alias sshuttle="python3 -m sshuttle"
alias c="clear"
alias p="python"
alias l="ls"
alias ll="ls -lh"
alias rcon="p ~/.config/i3/clubby_remote.py"
alias ssh-clear-masters="rm ~/.ssh/controlmasters/*"
alias nuclear-option="~/.config/i3/nuclear-option.sh"
alias acmpaste="curl --data-binary @- https://p.acm.umn.edu/"
alias aru="~/Documents/arduino-1.8.5/arduino --port /dev/ttyACM0 --board arduino:avr:leonardo --verbose-upload --upload"
alias sshuttle-home="sshuttle --dns -r scriber 0/0 -x home.louis.goessling.com"
alias ssh-start-agent="ssh-agent -k ; ssh-agent > ~/.ssh-agent-info && source ~/.ssh-agent-info && ssh-add"
alias kill-agents="bash ~/.config/i3/paranoia.sh"
alias kb=keybase
alias sshuttle-acm="sshuttle --dns -r hylaea 0/0 -x 160.94.179.187"
alias sshuttle-acm-mgmt="sshuttle -r lightman@160.94.179.147 10.99.99.0/24"
alias sshuttle-dept-db="sshuttle -r argo 192.168.216.42"

genpasswd () {
	echo $(head /dev/urandom -c ${1:-20} | base64 | head - -c ${1:-20})
}

batt () {
	upower -i $(upower -e | grep BAT)
}

runc () {
	gcc -Wall -Wextra -g $1 && ./a.out $2
}
clubbyplay () {
	scp $1 clubby:
	ssh clubby mpv $1 $2>1 1>/dev/null
}

alias clp=clubbyplay

getcert () {
	echo | openssl s_client -showcerts -servername $1 -connect $1:443 2>/dev/null | openssl x509 -inform pem -noout -text
}

alias d="banner d"

alias resource="source ~/.bashrc"
alias nbfc=/opt/nbfc/nbfc.exe

vpn () {
	sudo systemctl $1 openvpn-client@scriber
}

vpn-set-noleak-off () {
	sudo ufw default allow incoming
	sudo ufw default allow outgoing
	sudo ufw delete deny 53
	sudo ufw delete deny 53
}

vpn-set-noleak-on () {
	HOMEIP=$(cat ~/.homeip)
	sudo ufw default deny incoming
	sudo ufw default deny outgoing

	sudo ufw allow in on tun0
	sudo ufw allow out on tun0

	sudo ufw allow in from $HOMEIP
	sudo ufw allow out to $HOMEIP

	sudo ufw deny 53
	sudo ufw allow in on tun0 from 10.0.0.1 port 53
	sudo ufw allow out on tun0 to 10.0.0.1 port 53
	sudo conntrack -D
	sudo conntrack -D
	sudo conntrack -D
}

ufw-flush () {
	sudo ufw reset
	sudo ufw enable
}

vpn-refresh-ip () {
	HOMEIP=$(dig +short home.louis.goessling.com | sed -n 2p)
	echo "remote $HOMEIP 1194 udp" | sudo tee /etc/openvpn/client/scriber-ip.conf.patch
	echo "$HOMEIP" > ~/.homeip
}

cpu-set-govenor-performance () {
	sudo cpupower frequency-set -g performance
}

cpu-set-govenor-powersave () {
	sudo cpupower frequency-set -g powersave
}

cpu-set-upper-limit () {
	sudo cpupower frequency-set -u $1
}

cpu-set-lower-limit () {
	sudo cpupower frequency-set -d $1
}

cpu-freq-info () {
	cpupower frequency-info | egrep "should be within|kernel"
}
